### PR TITLE
Update jems to latest. #4

### PR DESCRIPTION
**Pull request by lemonboston**
It doesn't build at the moment because of:
```
Caused by: com.android.dex.DexException: Multiple dex files define Lorg/dmfs/optional/adapters/FirstPresent;
```

Most of the changes here are because after I couldn't fix the build, I though I update to latest gradle maybe that helps. But it didn't.
So `iterators` is excluded from codeka:carrot, and gradle dependencyInsight tells this as well, still during dexing the classes show up (it was ArrayIterable as well).

### CODE REVIEW

**Comment by lemonboston** [comment]
With latest contentpal, there is no exclude needed for them as you suggested. Ready for review.
Note: --refresh-dependencies gradle option was needed for the build to fetch the latest the -SNAPSHOT version.

**Comment by dmfs** [comment]
Better get rid if the `-SNAPSHOT` and specify a commit number instead. We don't want to break this because we made additional commits to ContentPal.

**Comment by lemonboston** [comment]
Remove `-SNAPSHOT` and using specific commit now for contentpal.

**Review by dmfs — APPROVED** [review]
Looks good.

**Pull request merged**
